### ISSUE TITLE
help for phonon spectral function of single phonon mode

### ISSUE THREAD

**Issue by DFT13** [SMTG-Bham/ThermoParser#102]
Dear kbspooner, I wonder how to plot the frequency-depencent phonon spectral function of single phonon mode, like this, can you give me some suggestions? 
![b3995b528c6e2fe3f5561d335f662a4](https://github.com/SMTG-Bham/ThermoParser/assets/69805655/d1fef00e-ddd6-4d09-a6c5-c18c2fb7e371)

**Comment by kbspooner** [comment]
I suppose that depends on the format of your data. If you can put it into a plain text file of the same format as the phonopy `projected_dos.dat` it could be plotted fairly directly with ThermoParser, or depending on your confidence with python (or desire to learn) you could write a small function to load it into the ThermoParser format and plot it in the same way. In the latter case I would be happy to incorporate it into this code (and credit you, of course). Hope this helps!
