### ISSUE TITLE
[joss review] Dependencies for building the documentation

### ISSUE THREAD

**Issue by fnattino** [SMTG-Bham/ThermoParser#80]
In order to build the documentation, the package `sphinx_rtd_theme` is required in addition to sphinx, but not mentioned anywhere. 

Also, sphinx is listed as part of the `requirements.txt` file, but you might consider creating instead a dependency set dedicated to building the documentation. See e.g. the [setuptools `extras_require` field](https://setuptools.pypa.io/en/latest/userguide/dependency_management.html#optional-dependencies). 

For instance, you could add to `setup.py`:

```python
setup(
  ...
  extras_require={
    "docs"=["sphinx", "sphinx_rtd_theme"]
  }
  ...
)
``` 

to be able to install docs-related dependencies using:  `pip install .[docs]`

[JOSS review issue](https://github.com/openjournals/joss-reviews/issues/6340)

**Comment by kbspooner** [comment]
Ahh this is handy, I've done this for the docs and the tests and updated the relevent docs sections, currently in the bug-fix branch.

**Comment by fnattino** [comment]
Great, nice setup! Concerning the tests: I think `unittest` is already part of the standard library, you should not need any additional dependency to run tests via `python -m unittest`, correct? Also note the different spelling of the `unitest` package you have now as extra dependency (only one "t"), not sure whether this is actually needed?

**Comment by kbspooner** [comment]
Ahh is that what happened. I got an error when I tried to install unittest, presumably because its built-in as you say, and it suggested unitest instead, so I blindly followed. I think I've done that before actually, but I will remember next time! Thanks!
