### ISSUE TITLE
[joss review] CI

### ISSUE THREAD

**Issue by fnattino** [SMTG-Bham/ThermoParser#81]
I see a `.travis.yml` file listing an old Python version in the root of the repository and a Travis CI badge with a broken link in the README - is Travis still used to automatically run tests? Maybe switch to GitHub actions (which is available for free)?   

[JOSS review issue](https://github.com/openjournals/joss-reviews/issues/6340)

**Comment by kbspooner** [comment]
Didn't reallise it had expired, switched to github actions. I also added actions for building and updating docs, and added badges for all three on the front page. It also recreated the install error @espottesmith encountered but I couldn't previously recreate, which I'll try to fix later.
