### ISSUE TITLE
[joss review] Python API documentation

### ISSUE THREAD

**Issue by fnattino** [SMTG-Bham/ThermoParser#82]
The [Python Package](https://smtg-bham.github.io/ThermoParser/modules.html) section of the documentation is quite difficult to read. Could it be improved by improving structuring and/or formatting? 

For instance, functions seems to be listed twice in each module, the first time of which without any description/information (see e.g. https://smtg-bham.github.io/ThermoParser/tp.axes.html#functions). Also, some descriptions are quite "uninformative" (e.g. the top one: https://smtg-bham.github.io/ThermoParser/tp.html#tp-package), maybe these could be removed.

Also, I would name this section "Python API" in order to make it clearer what this section is actually about.  

[JOSS review issue](https://github.com/openjournals/joss-reviews/issues/6340)

**Comment by kbspooner** [comment]
Ah this seems to be a hangover from before using sphinx. I've removed all of the duplication (I think) and modified some of the docstrings, as well as the Python API title.

**Comment by fnattino** [comment]
Nice, much more readable now, thanks!
