### ISSUE TITLE
[joss review] how is the documentation built

### ISSUE THREAD

**Issue by fnattino** [SMTG-Bham/ThermoParser#84]
As far as I understand the docs are published on GitHub pages without using Jekyll (I also see the `.nojekyll` file), but there is a Jekyll config file in `docs/_config.yml`? 

Also, why the folder `docs/src/_build` is checked in the repository? The build documentation is all available in `docs` , correct?

[JOSS review issue](https://github.com/openjournals/joss-reviews/issues/6340)

**Comment by kbspooner** [comment]
The docs folders were a mess! I've extended the changes mentioned in [issue 85](https://github.com/SMTG-Bham/ThermoParser/issues/85) to streamline the docs, and deleted some extra directories which must have been generated by me compiling them wrong and then never deleted.
