### ISSUE TITLE
[joss review] Tutorial X

### ISSUE THREAD

**Issue by fnattino** [SMTG-Bham/ThermoParser#89]
While the title of the tutorial mentions VASP, the content seems to be on rather diverse topics and not necessarily related to VASP. Can a more suitable section be identified for such topics?  

[JOSS review issue](https://github.com/openjournals/joss-reviews/issues/6340)

**Comment by kbspooner** [comment]
Ahh true. I've taken the lazy way out and renamed the whole section to miscellaneous assists.

**Comment by fnattino** [comment]
Looks good, now a user reading the docs won't be surprised when opening that section. Thanks!
