### ISSUE TITLE
ThermoParser version

### ISSUE THREAD

**Issue by fnattino** [SMTG-Bham/ThermoParser#95]
At the moment, there seems to be no direct way to access the package version from within Python,  correct? 

If would be nice if ThermoParser would follow the quasi-standard approach of providing the package version via the dunder `tp.__version__` (typically returning a string)

**Comment by fnattino** [comment]
Also, it is also very common to have a CLI option `--version` returning the version of the package.

**Comment by kbspooner** [comment]
These are now implemented. Thanks!
