### ISSUE TITLE
How to customize the range of the y-axis of wideband phonon?

### ISSUE THREAD

**Issue by DFT13** [SMTG-Bham/ThermoParser#99]
!Dear, when running "tp plot wideband band.yaml kappa-m101010_34ph.hdf5 -c inferno --poscar POSCAR", I find the range of energy doesnot suitable. So how to customize the range of the y-axis of wideband phonon? con you give me some suggestion?  [47c5e69565a11730efb3da9bc9fd45b](https://github.com/SMTG-Bham/ThermoParser/assets/69805655/a6626124-8bad-4848-8453-d376bda8433a)

**Comment by kbspooner** [comment]
Thats some strong scattering you have there!
Actually I neglected to add that ability, but that is now corrected, both in the wideband plot and the regular phonon plot on the master branch.
Simply add ``--ymin`` and/or ``--ymax`` and the appropriate value (there are also equivalent options for the x axis).
Thanks for pointing this out!

**Comment by DFT13** [comment]
it is fine! thanks very much
